import {
  REPORT_TEMPLATES,
  SHEQ_TEMPLATES,
  SHEQ_INSPECTION_CATEGORY,
  SHEQ_INSTALLATION_CATEGORY,
  TEMPLATE_LIBRARY,
  TEMPLATE_LIBRARY_BY_TITLE,
  filterTemplateLibrary,
} from "./templateCatalog";
import { GENERAL_FORM_TEMPLATES } from "./generalFormTemplates";

export { SHEQ_TEMPLATES as MONITORING_SHEQ_FORMS, SHEQ_INSPECTION_CATEGORY, SHEQ_INSTALLATION_CATEGORY };
export const MONITORING_REPORT_FORMS = REPORT_TEMPLATES;
export const MONITORING_FORM_TEMPLATES = TEMPLATE_LIBRARY;
export const MONITORING_FORM_TEMPLATE_BY_TITLE = TEMPLATE_LIBRARY_BY_TITLE;

export { filterTemplateLibrary as filterMonitoringTemplates };
