/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ConcernsRouteImport } from './routes/concerns'
import { Route as FormBuilderRouteImport } from './routes/form-builder'
import { Route as KpisRouteImport } from './routes/kpis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NonConformancesRouteImport } from './routes/non-conformances'
import { Route as PerformanceMonitoringRouteImport } from './routes/performance-monitoring'
import { Route as SheqFormsRouteImport } from './routes/sheq-forms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcernsRoute = ConcernsRouteImport.update({
  id: '/concerns',
  path: '/concerns',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderRoute = FormBuilderRouteImport.update({
  id: '/form-builder',
  path: '/form-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const KpisRoute = KpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NonConformancesRoute = NonConformancesRouteImport.update({
  id: '/non-conformances',
  path: '/non-conformances',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceMonitoringRoute = PerformanceMonitoringRouteImport.update({
  id: '/performance-monitoring',
  path: '/performance-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const SheqFormsRoute = SheqFormsRouteImport.update({
  id: '/sheq-forms',
  path: '/sheq-forms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/concerns': typeof ConcernsRoute
  '/form-builder': typeof FormBuilderRoute
  '/kpis': typeof KpisRoute
  '/login': typeof LoginRoute
  '/non-conformances': typeof NonConformancesRoute
  '/performance-monitoring': typeof PerformanceMonitoringRoute
  '/sheq-forms': typeof SheqFormsRoute
  '/signup': typeof SignupRoute
  '/sites': typeof SitesRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/concerns': typeof ConcernsRoute
  '/form-builder': typeof FormBuilderRoute
  '/kpis': typeof KpisRoute
  '/login': typeof LoginRoute
  '/non-conformances': typeof NonConformancesRoute
  '/performance-monitoring': typeof PerformanceMonitoringRoute
  '/sheq-forms': typeof SheqFormsRoute
  '/signup': typeof SignupRoute
  '/sites': typeof SitesRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/concerns': typeof ConcernsRoute
  '/form-builder': typeof FormBuilderRoute
  '/kpis': typeof KpisRoute
  '/login': typeof LoginRoute
  '/non-conformances': typeof NonConformancesRoute
  '/performance-monitoring': typeof PerformanceMonitoringRoute
  '/sheq-forms': typeof SheqFormsRoute
  '/signup': typeof SignupRoute
  '/sites': typeof SitesRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/concerns'
    | '/form-builder'
    | '/kpis'
    | '/login'
    | '/non-conformances'
    | '/performance-monitoring'
    | '/sheq-forms'
    | '/signup'
    | '/sites'
    | '/templates'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/concerns'
    | '/form-builder'
    | '/kpis'
    | '/login'
    | '/non-conformances'
    | '/performance-monitoring'
    | '/sheq-forms'
    | '/signup'
    | '/sites'
    | '/templates'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/concerns'
    | '/form-builder'
    | '/kpis'
    | '/login'
    | '/non-conformances'
    | '/performance-monitoring'
    | '/sheq-forms'
    | '/signup'
    | '/sites'
    | '/templates'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRoute
  ConcernsRoute: typeof ConcernsRoute
  FormBuilderRoute: typeof FormBuilderRoute
  KpisRoute: typeof KpisRoute
  LoginRoute: typeof LoginRoute
  NonConformancesRoute: typeof NonConformancesRoute
  PerformanceMonitoringRoute: typeof PerformanceMonitoringRoute
  SheqFormsRoute: typeof SheqFormsRoute
  SignupRoute: typeof SignupRoute
  SitesRoute: typeof SitesRoute
  TemplatesRoute: typeof TemplatesRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerns': {
      id: '/concerns'
      path: '/concerns'
      fullPath: '/concerns'
      preLoaderRoute: typeof ConcernsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-builder': {
      id: '/form-builder'
      path: '/form-builder'
      fullPath: '/form-builder'
      preLoaderRoute: typeof FormBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpis': {
      id: '/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof KpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/non-conformances': {
      id: '/non-conformances'
      path: '/non-conformances'
      fullPath: '/non-conformances'
      preLoaderRoute: typeof NonConformancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance-monitoring': {
      id: '/performance-monitoring'
      path: '/performance-monitoring'
      fullPath: '/performance-monitoring'
      preLoaderRoute: typeof PerformanceMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheq-forms': {
      id: '/sheq-forms'
      path: '/sheq-forms'
      fullPath: '/sheq-forms'
      preLoaderRoute: typeof SheqFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRoute,
  ConcernsRoute: ConcernsRoute,
  FormBuilderRoute: FormBuilderRoute,
  KpisRoute: KpisRoute,
  LoginRoute: LoginRoute,
  NonConformancesRoute: NonConformancesRoute,
  PerformanceMonitoringRoute: PerformanceMonitoringRoute,
  SheqFormsRoute: SheqFormsRoute,
  SignupRoute: SignupRoute,
  SitesRoute: SitesRoute,
  TemplatesRoute: TemplatesRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
